.TH APPCTL-CREATE 1
.SH NAME
appctl create - creates an empty application container.
.SH SYNOPSIS
appctl
[\fB\-v|\-\-verbose\fR]...
create
\fIcontainer\fR
[\fIpath\fR]
.SH DESCRIPTION
\fBappctl create\fR creates a new container, optionally from a specified folder.
.SH OPTIONS
General options are written before the command, and specific options are written
after the command.
.SS General options
.TP
.BR \-v\fR, " " \fB\-\-verbose\fR
Logs out more information (multiple \fB\-v\fR or \fB\-\-verbose\fR will result
in even more information being logged).
.SS Specific options
.TP
.IR container\fR
The container to create.
.TP
.IR path
The directory to use as a template for the container.
.SH ENVIRONMENT
.TP
.BR APPCTL_GENERAL_OPTS
If \fB$APPCTL_GENERAL_OPTS\fR is set, the value of it will be appended to the
general options provided from command line.
.TP
.BR APPCTL_CREATE_OPTS
If \fB$APPCLT_CREATE_OPTS\fR is set, the value of it will be appended to the
specific options.
.TP
.BR APPCTL_SOCKET
If \fB$APPCLT_SOCKET\fR is set, its value will be used as the socket to connect
to instead of the default socket.
.SH SEE ALSO
.BR appctl\fR(1)
