.TH APPCTL-PULLF 1
.SH NAME
appctl pullf - reads a file from another application container.
.SH SYNOPSIS
appctl
[\fB\-v|\-\-verbose\fR]...
pullf
\fIcontainer\fR
\fIpath\fR
[\fIdestination\fR]
.SH DESCRIPTION
\fBappctl pullf\fR reads a file from another container and saves it to a path in
the current container, or prints it to STDOUT.
.SH OPTIONS
General options are written before the command, and specific options are written
after the command.
.SS General options
.TP
.BR \-v\fR, " " \fB\-\-verbose\fR
Logs out more information (multiple \fB\-v\fR or \fB\-\-verbose\fR will result
in even more information being logged).
.SS Specific options
.TP
.IR container
The container to read the file from
.TP
.IR path
The path of the file in the \fIcontainer\fR to read the file from.
.TP
.IR destination
The path to save the file to.  If this is not specified, the file contents will
be sent over STDOUT.
.SH ENVIRONMENT
.TP
.BR APPCTL_GENERAL_OPTS
If \fB$APPCTL_GENERAL_OPTS\fR is set, the value of it will be appended to the
general options provided from command line.
.TP
.BR APPCTL_PULLF_OPTS
If \fB$APPCLT_PULLF_OPTS\fR is set, the value of it will be appended to the
specific options.
.TP
.BR APPCTL_SOCKET
If \fB$APPCLT_SOCKET\fR is set, its value will be used as the socket to connect
to instead of the default socket.
.SH SEE ALSO
.BR appctl\fR(1)
