.TH APPCTL-PUSHF 1
.SH NAME
appctl pushf - writes a file to another application container.
.SH SYNOPSIS
appctl
[\fB\-v|\-\-verbose\fR]...
pushf
\fIcontainer\fR
\fIpath\fR
[\fIsource\fR]
.SH DESCRIPTION
\fBappctl pushf\fR saves a file to another container from a path in the current
container, or from STDIN.
.SH OPTIONS
General options are written before the command, and specific options are written
after the command.
.SS General options
.TP
.BR \-v\fR, " " \fB\-\-verbose\fR
Logs out more information (multiple \fB\-v\fR or \fB\-\-verbose\fR will result
in even more information being logged).
.SS Specific options
.TP
.IR container
The container to write the file to
.TP
.IR path
The path of the file in the \fIcontainer\fR to write the file to.
.TP
.IR source
The path to read the file from.  If this is not specified, the file contents
will be read from STDIN.
.SH ENVIRONMENT
.TP
.BR APPCTL_GENERAL_OPTS
If \fB$APPCTL_GENERAL_OPTS\fR is set, the value of it will be appended to the
general options provided from command line.
.TP
.BR APPCTL_PUSHF_OPTS
If \fB$APPCLT_PUSHF_OPTS\fR is set, the value of it will be appended to the
specific options.
.TP
.BR APPCTL_SOCKET
If \fB$APPCLT_SOCKET\fR is set, its value will be used as the socket to connect
to instead of the default socket.
.SH SEE ALSO
.BR appctl\fR(1)
